namespace CoCCGen.Core;

public static class Characters {
    public static readonly string[] Ideas = new[] {
        "A nervous librarian, a woman in her 30s.",
        "A skeptical journalist, a man in his late 20s.",
        "A reclusive artist, a man in his 40s.",
        "A daring private investigator, a woman in her 30s.",
        "A secretive cultist, an elderly woman.",
        "A paranoid war veteran, a man in his 50s.",
        "A curious young scholar, a woman in her early 20s.",
        "A cynical detective, a man in his 40s.",
        "A wealthy dilettante, a man in his 30s.",
        "A resourceful mechanic, a woman in her late 20s.",
        "A troubled medium, a woman in her 40s.",
        "A brilliant scientist, a man in his 50s.",
        "A determined archaeologist, a woman in her 30s.",
        "A mysterious occultist, a man in his 60s.",
        "A charming con artist, a man in his 20s.",
        "A brave ex-soldier, a woman in her 40s.",
        "A timid nurse, a woman in her 30s.",
        "A charismatic preacher, a man in his 50s.",
        "A secretive government agent, a man in his 40s.",
        "A curious antique dealer, a woman in her 50s.",
        "A fearless stunt pilot, a man in his 30s.",
        "A reclusive cryptozoologist, a woman in her 40s.",
        "A haunted author, a man in his 50s.",
        "A superstitious fisherman, a man in his 60s.",
        "A rebellious flapper, a woman in her 20s.",
        "A clever street magician, a man in his 30s.",
        "A cautious botanist, a woman in her 40s.",
        "A pragmatic police officer, a man in his 30s.",
        "A troubled psychologist, a woman in her 50s.",
        "A flamboyant stage performer, a man in his 40s.",
        "A weary sailor, a man in his 50s.",
        "An ambitious journalist, a woman in her 20s.",
        "A stoic blacksmith, a man in his 40s.",
        "A jittery stagehand, a man in his 30s.",
        "A sharp-eyed art curator, a woman in her 50s.",
        "A calculating mobster, a man in his 40s.",
        "An eccentric inventor, a man in his 60s.",
        "A compassionate social worker, a woman in her 30s.",
        "A determined mountain climber, a woman in her 40s.",
        "A clairvoyant child, a girl of 12.",
        "A pragmatic nurse, a man in his 30s.",
        "A haunted gravedigger, a man in his 50s.",
        "A meticulous jeweler, a woman in her 40s.",
        "A bold aviator, a woman in her 30s.",
        "A soft-spoken pastor, a man in his 60s.",
        "An observant watchmaker, a man in his 50s.",
        "A cryptic fortune teller, a woman in her 60s.",
        "A skeptical mathematician, a man in his 40s.",
        "An adventurous explorer, a woman in her 30s.",
        "A stern schoolteacher, a woman in her 50s.",
        "A haunted exorcist, a man in his 40s.",
        "An elusive smuggler, a woman in her 20s.",
        "A retired boxer, a man in his 50s.",
        "A calculating pharmacist, a man in his 30s.",
        "An inquisitive geologist, a woman in her 40s.",
        "A mysterious beekeeper, a woman in her 50s.",
        "A loyal butler, a man in his 60s.",
        "An ambitious film director, a woman in her 30s.",
        "A jaded stage actress, a woman in her 40s.",
        "An enigmatic chess master, a man in his 70s.",
        "A boisterous bartender, a man in his 40s.",
        "A skeptical historian, a woman in her 50s.",
        "A secretive herbalist, a woman in her 60s.",
        "A troubled ex-convict, a man in his 30s.",
        "A fearless circus performer, a woman in her 20s.",
        "A grim-faced mortician, a man in his 50s.",
        "An ambitious architect, a woman in her 40s.",
        "A neurotic playwright, a man in his 30s.",
        "A mysterious lighthouse keeper, a man in his 60s.",
        "A cunning thief, a woman in her 20s.",
        "A reclusive astronomer, a woman in her 50s.",
        "An inquisitive journalist, a man in his 30s.",
        "A loyal chauffeur, a man in his 40s.",
        "A compassionate nun, a woman in her 50s.",
        "A grizzled fisherman, a man in his 60s.",
        "An eccentric clockmaker, a man in his 70s.",
        "A daring photojournalist, a woman in her 30s.",
        "A haunted exorcist, a woman in her 40s.",
        "A secretive undertaker, a man in his 50s.",
        "An enigmatic diplomat, a man in his 40s.",
        "A charismatic politician, a woman in her 50s.",
        "A resourceful survivalist, a man in his 30s.",
        "A superstitious maid, a woman in her 20s.",
        "A reclusive novelist, a woman in her 60s.",
        "A fearless firefighter, a man in his 30s.",
        "A stern judge, a woman in her 50s.",
        "A curious zoologist, a woman in her 40s.",
        "A cheerful baker, a man in his 30s.",
        "A meticulous accountant, a woman in her 40s.",
        "A retired adventurer, a man in his 70s.",
        "A dedicated school principal, a man in his 50s.",
        "A shrewd lawyer, a woman in her 30s.",
        "A quirky puppeteer, a man in his 40s.",
        "A passionate chef, a woman in her 30s.",
        "An eccentric antique collector, a man in his 60s.",
        "A bold mountain guide, a woman in her 40s.",
        "A philosophical monk, a man in his 50s.",
        "A wise elder, a woman in her 70s.",
        "A fierce boxer, a woman in her 30s.",
        "A retired professor, a man in his 60s.",
        "A mysterious artifact hunter, a woman in her 40s.",
        "A dashing naval officer, a man in his 30s.",
        "A haunted violinist, a woman in her 20s.",
        "An enthusiastic botanist, a man in his 30s.",
        "A world-weary detective, a man in his 50s.",
        "A cunning illusionist, a woman in her 30s.",
        "A determined ship captain, a man in his 40s.",
        "A reclusive potter, a woman in her 50s.",
        "A soft-spoken gardener, a man in his 60s.",
        "A brilliant chemist, a woman in her 40s.",
        "A sickly librarien with a limp, 50s woman.",
        "A charming gambler, a man in his 30s.",
        "A pragmatic nurse, a woman in her 40s.",
        "An insightful psychiatrist, a man in his 50s.",
        "A daring stunt double, a woman in her 20s.",
        "A skeptical meteorologist, a man in his 40s.",
        "A superstitious fortune teller, a woman in her 60s.",
        "A mysterious sailor, a woman in her 50s.",
        "An enigmatic archaeologist, a man in his 30s.",
        "A brooding artist, a woman in her 40s.",
        "A resourceful mechanic, a man in his 30s.",
        "A haunted pianist, a woman in her 20s.",
        "A charismatic auctioneer, a man in his 50s.",
        "A jaded hotel manager, a woman in her 40s.",
        "A bold treasure hunter, a man in his 30s.",
        "A wise old librarian, a woman in her 70s.",
        "A suspicious shopkeeper, a man in his 50s.",
        "A passionate dancer, a woman in her 20s.",
        "A retired jewel thief, a man in his 60s.",
        "A secretive cult leader, a man in his 50s.",
        "A quirky inventor, a woman in her 40s.",
        "A grumpy taxi driver, a man in his 50s.",
        "A compassionate veterinarian, a woman in her 30s.",
        "A mysterious drifter, a man in his 40s.",
        "A determined park ranger, a woman in her 30s.",
        "An eccentric playwright, a man in his 60s.",
        "A fearless circus ringmaster, a woman in her 50s.",
        "A brooding poet, a man in his 30s.",
        "A cautious security guard, a woman in her 40s.",
        "A skeptical skeptic, a man in his 50s.",
        "A philosophical chess player, a woman in her 60s.",
        "A pragmatic coroner, a man in his 40s.",
        "An adventurous spelunker, a woman in her 30s.",
        "A haunted lighthouse keeper, a man in his 50s.",
        "A cunning escape artist, a woman in her 20s.",
        "A grizzled prospector, a man in his 60s.",
        "A dedicated dog trainer, a woman in her 30s.",
        "A reclusive hermit, a man in his 70s.",
        "A daring race car driver, a woman in her 20s.",
        "A charming travel writer, a man in his 40s.",
        "A secretive intelligence officer, a woman in her 30s.",
        "A skeptical astronomer, a man in his 50s.",
        "A curious folklore expert, a woman in her 40s.",
        "A world-weary bounty hunter, a man in his 40s.",
        "A compassionate midwife, a woman in her 50s.",
        "A haunted toy maker, a man in his 60s.",
        "An enigmatic swordsman, a woman in her 30s.",
        "A brooding bartender, a man in his 40s.",
        "A wise herbalist, a woman in her 60s.",
        "A daring hot air balloonist, a man in his 30s.",
        "A mysterious puppeteer, a woman in her 50s.",
        "A haunted clockmaker, a man in his 50s, who meticulously creates intricate timepieces in his secluded workshop, each with a strange, almost mystical quality.",
        "An eccentric old widow, a woman in her 70s, who lives in a crumbling mansion filled with rare and unusual books, rumored to be a collector of forbidden knowledge.",
        "A charismatic circus performer, a man in his 30s, known for his death-defying stunts and rumored to have a dark past involving a mysterious accident.",
        "A determined marine biologist, a woman in her 40s, who is driven by a quest to uncover the secrets of a deep-sea creature she once glimpsed as a child.",
        "A reclusive painter, a man in his 60s, whose works depict unsettling and surreal landscapes that seem to come to life under moonlight.",
        "A resourceful young mechanic, a woman in her 20s, who has a knack for fixing anything and an obsession with old, mysterious vehicles she finds in junkyards.",
        "A brooding poet, a man in his 40s, who writes dark, melancholic verses inspired by his encounters with otherworldly beings.",
        "A superstitious lighthouse keeper, a man in his 50s, who believes the light he tends protects the coast from ancient, unseen terrors.",
        "A bold explorer, a woman in her 30s, who is always seeking lost cities and forbidden tombs, driven by an insatiable curiosity and dreams of immortality.",
        "A secretive alchemist, a man in his 60s, who conducts strange experiments in his basement, claiming to be on the verge of discovering the elixir of life.",
        "A haunted violinist, a woman in her 20s, who plays melancholic melodies that seem to echo the voices of the departed.",
        "A pragmatic coroner, a man in his 40s, with an uncanny ability to deduce the stories of the dead from the slightest of clues, often leading him into dangerous mysteries.",
        "A skeptical paranormal investigator, a woman in her 30s, who uses cutting-edge technology to debunk supernatural occurrences, yet is haunted by an encounter she cannot explain.",
        "An enigmatic antiquarian, a man in his 50s, who deals in rare and cursed artifacts, and is rumored to have made a pact with dark forces for eternal youth.",
        "A fearless archaeologist, a woman in her 40s, who uncovers ancient relics and inscriptions that speak of forgotten gods and cosmic horrors.",
        "A grizzled ex-cop, a man in his 50s, turned private investigator, who now specializes in missing persons cases involving the supernatural.",
        "A curious botanist, a woman in her 30s, who has discovered plants with strange, sentient qualities in the heart of an uncharted jungle.",
        "A wealthy dilettante, a man in his 40s, who funds expeditions to uncover lost secrets and occult mysteries, driven by an obsession with the unknown.",
        "A haunted novelist, a woman in her 50s, who writes chilling tales that seem to come true, plagued by visions of the horrors she pens.",
        "A resourceful young thief, a woman in her 20s, who steals only from the homes of those rumored to harbor dark secrets or cursed treasures.",
        "An eccentric clockmaker, a man in his 60s, who believes his creations can manipulate time, and is constantly seeking to perfect a clock that can reverse his past mistakes.",
        "A stern librarian, a woman in her 40s, who guards a hidden section of her library containing forbidden texts and dangerous knowledge.",
        "A reclusive novelist, a man in his 50s, who writes best-selling horror novels based on true stories he's experienced but is too afraid to share.",
        "A cynical war veteran, a man in his 40s, who now runs a security firm and has seen things on the battlefield that haunt his every step.",
        "A determined nurse, a woman in her 30s, who works the night shift at an old hospital, caring for patients with bizarre and terrifying ailments.",
        "A flamboyant stage magician, a man in his 40s, who has mastered real magic and uses it to enhance his performances, often at great personal risk.",
        "A troubled priest, a man in his 50s, who performs exorcisms and battles demonic forces, often questioning his own faith in the process.",
        "A fearless firefighter, a woman in her 30s, who has developed a sixth sense for sensing danger and is haunted by visions of the fires she extinguishes.",
        "A quiet gravedigger, a man in his 50s, who has seen too many strange occurrences in the cemetery and keeps a journal of the undead he encounters.",
        "A curious folklorist, a woman in her 40s, who travels the world collecting and investigating local legends and myths, often finding more than she bargained for.",
        "A charismatic cult leader, a man in his 50s, who believes he is the reincarnation of an ancient deity and has a growing number of devoted followers.",
        "A driven paleontologist, a woman in her 30s, who uncovers fossils that don't match any known species and hint at dark, prehistoric secrets.",
        "An enigmatic puppeteer, a man in his 60s, whose marionettes seem almost alive and are said to move on their own when no one is watching.",
        "A pragmatic psychiatrist, a woman in her 40s, who treats patients with extreme psychological conditions linked to the paranormal.",
        "A determined mountain climber, a man in his 30s, who has a map to a peak that no one has ever returned from and is obsessed with reaching the summit.",
        "A stern school teacher, a woman in her 50s, who moonlights as a ghost hunter and has uncovered the dark history of her school.",
        "A reclusive cryptozoologist, a man in his 40s, who has captured evidence of creatures that science says shouldn't exist and is determined to prove their existence.",
        "A haunted ex-soldier, a woman in her 30s, who now works as a bodyguard and is constantly looking over her shoulder for the enemies she can't see.",
        "A brilliant chemist, a man in his 40s, who experiments with potions that have unpredictable and often dangerous effects.",
        "A curious young hacker, a woman in her 20s, who stumbles upon secret government files revealing the existence of supernatural phenomena.",
        "A grizzled prospector, a man in his 60s, who knows the location of a cursed mine and is determined to uncover its dark secrets.",
        "A talented chef, a woman in her 30s, who incorporates rare and forbidden ingredients into her dishes, each with mysterious and unpredictable effects.",
        "A jaded archaeologist, a man in his 40s, who seeks artifacts of power and has seen too many colleagues fall to the curses they carry.",
        "A compassionate nurse, a woman in her 30s, who volunteers at a haunted asylum and is drawn to the dark history of the place.",
        "A brooding detective, a man in his 50s, who solves crimes that involve the supernatural and often crosses paths with otherworldly beings.",
        "A cunning lawyer, a woman in her 40s, who specializes in defending clients accused of crimes involving the occult and has a reputation for winning even the most bizarre cases.",
        "An enigmatic blacksmith, a man in his 60s, who forges weapons imbued with magical properties and is rumored to have connections with ancient warrior spirits.",
        "A daring treasure hunter, a woman in her 30s, who searches for relics of ancient, forgotten civilizations and battles both human and supernatural foes.",
        "A haunted artist, a man in his 40s, who paints scenes of terror and despair, each canvas seemingly a window into a darker world.",
        "A reclusive beekeeper, a woman in her 50s, whose bees produce honey with strange, mind-altering properties, and who has a deep connection to nature's hidden mysteries.",
    };
}
